const translations = {
  en: {
    basedOn: 'Based on highest hiring standards',
    evaluator: 'Certified Interview Evaluator · Barbaros AI',
    speaking: '● Speaking...',
    listening: '○ Listening',
    processing: 'Processing...',
    showText: 'Show text',
    hideText: 'Hide text',
    candidate: 'Candidate',
    yourTurn: 'Your turn',
    listeningToAdam: 'Listening to Adam...',
    keepHolding: '● Keep holding until you finish your complete answer',
    holdHint: 'Hold for your complete answer — release only when done',
    recording: '● Recording...',
    typeHere: 'Or type your answer here...',
    micDenied: 'Microphone access denied — please allow mic permission',
    transcribeFailed: 'Transcription failed — please try again',
    sessionEnded: 'Session ended',
    score: 'Score',
    redirecting: 'Redirecting to your report...',
    viewReport: 'View Full Report →',
    performance: 'Performance',
    end: 'End',
    endConfirm: 'End interview?',
    question: 'Q',
    poweredBy: 'Developed by certified HR professionals, powered by AI',
  },
  ar: {
    basedOn: 'وفق أعلى معايير التوظيف',
    evaluator: 'مقيّم مقابلات معتمد · Barbaros AI',
    speaking: '● يتحدث...',
    listening: '○ يستمع',
    processing: 'جاري المعالجة...',
    showText: 'عرض النص',
    hideText: 'إخفاء النص',
    candidate: 'مرشح',
    yourTurn: 'دورك',
    listeningToAdam: 'يستمع لآدم...',
    keepHolding: '● استمر بالضغط حتى تنهي إجابتك كاملة',
    holdHint: 'اضغط مع الاستمرار للإجابة الكاملة — أفلت فقط عند الانتهاء',
    recording: '● جاري التسجيل...',
    typeHere: 'أو اكتب إجابتك هنا...',
    micDenied: 'تم رفض الوصول للميكروفون — يرجى السماح بالإذن',
    transcribeFailed: 'فشل التحويل — يرجى المحاولة مجدداً',
    sessionEnded: 'انتهت الجلسة',
    score: 'النتيجة',
    redirecting: 'جاري التحويل إلى تقريرك...',
    viewReport: 'عرض التقرير الكامل ←',
    performance: 'الأداء',
    end: 'إنهاء',
    endConfirm: 'إنهاء المقابلة؟',
    question: 'س',
    poweredBy: 'طُوِّر بمشاركة متخصصين معتمدين في الموارد البشرية، مدعوم بالذكاء الاصطناعي',
  }
}
